### ISSUE TITLE
Post-vote release checklist for version 2.0.1

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1846]
- [x] Label this issue with the [project](https://github.com/apache/accumulo/projects) that corresponds to this release version
- [Git](https://github.com/apache/accumulo) tasks
  - [x] Create a signed `rel/<version>` tag (and push it)
  - [x] Merge `<version>-rc<N>-next` branch into a maintenance branch (if maintenance is expected),
        and then into the `main` branch (and push them)
  - [x] Remove `*-rc*` branches
- [Nexus](https://repository.apache.org) tasks
  - [x] Release the staging repository corresponding to the successful release candidate (use "release" button)
  - [x] Drop any other staging repositories for Accumulo (do *not* "release" or "promote" them)
- [SVN / dist-release](https://dist.apache.org/repos/dist/release/accumulo) tasks
  - [x] Upload the release artifacts (tarballs, signatures, and `.sha512` files) for the mirrors
  - [x] Remove old artifacts from the mirrors (**after** updating the website)
- [Board reporting tool](https://reporter.apache.org/addrelease?accumulo)
  - [x] Add the date of release (the date the release artifacts were uploaded to SVN `UTC+0000`)
- Verify published artifacts
  - [x] In [Maven Central](https://repo1.maven.org/maven2/org/apache/accumulo/accumulo-core/)
  - [x] In [ASF Downloads](https://downloads.apache.org/accumulo)
  - [x] In [several mirrors](https://www.apache.org/dyn/closer.lua/accumulo)
- Update the [staging website](http://accumulo.staged.apache.org/)
  - [x] Release notes
  - [x] Add `LTS: true` to the release notes front-matter for LTS releases
  - [x] Navigation
  - [x] Downloads page
  - [x] DOAP file
  - [x] Add manual/examples/javadoc
  - [x] If javadoc is built with Java 11, [patch it](https://github.com/apache/accumulo/blob/main/contrib/javadoc11.patch)
  - [x] Jekyll config
  - [x] Grep for, and update any links to previous version to now point to the new version
  - [x] Update any older release notes front-matter to indicate they are either `archived: true` or `archived_critical: true`
  - [x] [Publish to production](https://github.com/apache/accumulo-website#publishing-staging-to-production)
- Announcement email
  - [x] Prepare and get review on dev list (see examples [from previous announcement messages](https://lists.apache.org/list.html?announce@apache.org:gte=1d:accumulo))
  - [x] Send to announce@apache.org and user@accumulo.apache.org
- GitHub wrap-up
  - [x] Close this issue
  - [x] Create a new "Automated Kanban" [project](https://github.com/apache/accumulo/projects) for the next version (if necessary) and move any open issues not completed in this release to that project
  - [x] Close the project that corresponds to this release
- Twitter
  - [x] [Tweet it](https://tweetdeck.twitter.com)
  - [x] [Confirm the tweet](https://twitter.com/ApacheAccumulo)

**Comment by ctubbsii** [comment]
In order to build the javadocs for 2.0.1 for the website using Java 15 (the latest available to me at the time), I had to backport the following javadoc fixes from the main branch:

```diff
diff --git a/core/src/main/java/org/apache/accumulo/core/data/doc-files/mutation-serialization.html b/core/src/main/java/org/apache/accumulo/core/data/doc-files/mutation-serialization.html
index f00d1b756e..d0ae38b176 100644
--- a/core/src/main/java/org/apache/accumulo/core/data/doc-files/mutation-serialization.html
+++ b/core/src/main/java/org/apache/accumulo/core/data/doc-files/mutation-serialization.html
@@ -19,6 +19,9 @@
     <title>Serialization Formats for Mutation</title>
   </head>
   <body>
+
+    <h1>Serialization Formats for Mutation</h1>
+
     <p>
     The <code>Mutation</code> class supports two serialization formats.
     While it only currently serializes to the newer version 2 format, it
diff --git a/pom.xml b/pom.xml
index 3a7d6e750d..4149430ed6 100644
--- a/pom.xml
+++ b/pom.xml
@@ -876,7 +876,7 @@
         <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-javadoc-plugin</artifactId>
-          <version>3.1.0</version>
+          <version>3.2.0</version>
           <configuration>
             <quiet>true</quiet>
             <additionalJOption>-J-Xmx512m</additionalJOption>
```

Building with the newer javadoc tool for the website is preferable to using an older JDK, because javadoc bug fixes aren't always backported to the older JDKs.
