### ISSUE TITLE
No-chop merge additional testing

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3766]
This is a follow on Issue for #3761 to add more testing to things identified that are lacking coverage. The following list is a wok in progress and will likely continue to be modified and grow as #3761 is reviewed. PRs can be created for of the items below.

- [ ] Test tablet import/export with non-infinite ranges. Addressed by: #3930
- [x] Test cloning a table with non-infinite ranges. Addressed by: #3925
- [x] Test merging the metadata table or see if those test exists.  Want to exercise metadata tablets with files that have non-infinite ranges. Addressed by #3931
- [x] Make sure automatic compactions are disabled during tests that verifiy rfile counts and metadata to avoid non-deterministic tests. This can be done by setting TABLE_MAJC_RATIO to a higher number than files created.  Original [comment](https://github.com/apache/accumulo/pull/3761#issuecomment-1732583551). Addressed by: #3775
- [x]  `MetadataConstraintTest` improvements mentioned in [comment](https://github.com/apache/accumulo/pull/3761#discussion_r1334838096), Addressed by #3774
- [x]  Test replacing a volume with tablets with non infinite ranges, see [comment](https://github.com/apache/accumulo/pull/3761#discussion_r1334856201). Addressed by #3793 
- [x]  Add tests for sampling that covers non infinite ranges, see [comment](https://github.com/apache/accumulo/pull/3761#discussion_r1334861348). Addressed by #3824 
- [x]  Test forcing an external compaction on a tablet with non infinite ranges, see  [comment](https://github.com/apache/accumulo/pull/3761#discussion_r1334844528) Addressed by: #3932
- [x] Increase unit test code coverage on new Fencing code in Rfile.  Ran rfile unit test w/ coverage on #3761 and noticed that FencedFileSKVIterator.getFirstKey() and getLastKey and a few other methods were not covered by unit test. Addressed by #3799
