### ISSUE TITLE
Tests table operations with lots of tablets

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3935]
Some table operations read and write to the metadata table. In order to verify that these operations do not buffer too much in memory, testing with a large number of tablets would be good.  Some of this testing is already done.  Some table operations may need to be adapted to use the conditional tablet update changes in #3929 that avoid buffering conditional update status in memory.

 - [X] Delete table done in #3929
 - [X] Merge done in #3934
 - [X] Clone done in #3934 
 - [ ] Bulk import
 - [ ] Compact
 - [ ] Delete rows 
 - [ ] import/export
 - [ ] offline/online 

More test can be added to SplitMillionIT for the above cases.

**Comment by keith-turner** [comment]
Another useful test may be to create a table w/ lots of tablet, clone and truncate it. This simulates the situation where the user wants to create a copy of a range of a large table.
